### ISSUE TITLE
Probleme mit "/alias" zu "/alias/" 

### ISSUE THREAD

**Issue by grummbeer** [terminal42/contao-url-rewrite#34]
Hi Leute,

folgender Fall: Das Suffix wurde von `.html` nach `/` umgestellt. Dafür habe ich eine Regel angelegt.

- Contao 4.9
- URL rewrite 1.6.6

```yaml
# app/config/parameters.yaml
contao:
    url_suffix: "/"
```

```
Pfad: 
     /{path}{suffix}
Extra:
   - path: .*
   - suffix: \.html$
Antwort-URL:
    /{path}/
```
Das hat soweit funktioniert. Wenn es besser geht, bin ich offen für Vorschläge :-)

Nun gibt es aber Seiten, deren Alias ohne `.html` in z.B. Printmedien verwendet wurde.

Beispiel:

```
Pfad: 
     /datenschutz
Antwort-URL:
    /{{link_url::123}}
```

Das hat zuverlässig dafür gesorgt (Danke!), dass der URL `/datenschutz` zu `/datenschutz.html` umgelenkt wurde.

Erwartet hatte ich jetzt, dass diese Regel auch mit dem `/` als suffix einfach weiterhin funktioniert. Tut sie aber nicht, nun produziert die Regel eine Schleife: `ERR_TOO_MANY_REDIRECTS`.

- datenschutz 301
- datenschutz/ 301
- datenschutz 301
- datenschutz/ 301
- …

Beide URLs werden getroffen. Das Einschränken des URL scheint auch nicht zu funktionieren.

```
Pfad: 
     /{path}
Extra:
   - path: datenschutz$
Antwort-URL:
    /{{link_url::123}}
```

Was mache ich falsch?

**Comment by Toflar** [comment]
Das hier ist der Bugtracker. Für Support: https://contao.org/de/support.html

**Comment by aschempp** [comment]
soweit mir bekannt ist, schreibt Contao (bzw. Symfony) eine URL ohne Slash automatisch auf mit Slash um, wenn dieser konfiguriert ist. Hast du es mal ohne URL-Rewrite versucht?

**Comment by grummbeer** [comment]
Hab’s in einer frischen 5.4er Installation ausprobiert.

```yaml
app_slashless:
  path: /slashless
  controller: App\Controller\SlashController::slashless
app_slash:
  path: /slash/
  controller: App\Controller\SlashController::slash
```

Ich kann bestätigen, dass beide Routen genau wie hier¹ beschrieben funktionieren und jeweils einen Redirect auslösen.

```
/slashless/ > 301 > /slashless
/slash > 301 > /slash/
```

Contao verhält sich so nicht. Soll ich da ein Ticket im Contao repo aufmachen?


¹ https://symfony.com/doc/5.4/routing.html#redirecting-urls-with-trailing-slashes
